### ISSUE TITLE
Transfer ownership of meevax_vendor package

### ISSUE THREAD

**Issue by hakuturu583** [yamacir-kit/meevax#279]
I succeed to develop meevax_vendor package and we can use meevax with ROS2 framework.

https://github.com/hakuturu583/meevax_vendor

I think it is better to transfer ownership to you.

How do you think about it?

**Comment by yamacir-kit** [comment]
Thanks for your contribution to Meevax.

First, while working with ROS2 is one of our future goals, it is not a current development focus. As such, I can't promise anything more than minimal maintenance if ownership of the repository is transferred to me. Also, in a worst case scenario, the Meevax ROS2 integration itself may be dropped from the target.

If you agree to the above, then there is no problem in transferring ownership of meevax_vendor to my GitHub account.

If you want to ensure that meevax_vendor is maintained and actively enhanced, I suggest you maintain it yourself.
